db:
  image: mysql:5.6
  environment:
  - MYSQL_ROOT_PASSWORD=mysecretpassword
  - MYSQL_DATABASE=ushahidi
  - MYSQL_USER=ushahidi-user
  - MYSQL_PASSWORD=ushahidi-db-password

platform:
  build: platform
  ports:
  - 8080:80
  environment:
  - DB_HOST=db
  - DB_NAME=ushahidi
  - DB_TYPE=MySQLi
  - DB_USER=ushahidi-user
  - DB_PASS=ushahidi-db-password
  #volumes:
  #- /home/user/docker-ushahidi/platforms/src:/var/www/html
  links:
  - db:db

client:
  #image: nginx
  build: client
  ports: 
  - 80:80
  #volumes:
  #- /home/user/docker-ushahidi/platform-client/server/www:/usr/share/nginx/html
  environment:
  - BACKEND_URL=http://138.201.159.97:8080/v3
