db:
  image: staff0rd/mysql-minimal
  environment:
  - MYSQL_ROOT_PASSWORD=mysecretpassword
  - MYSQL_DATABASE=ushahidi
  - MYSQL_USER=ushahidi-user
  - MYSQL_PASSWORD=ushahidi-db-password

platform:
  #build: platform
  image: bennibu/ushahidi-platform
  ports:
  - 8080:80
  environment:
  - DB_HOST=db
  - DB_NAME=ushahidi
  - DB_TYPE=MySQLi
  - DB_USER=ushahidi-user
  - DB_PASS=ushahidi-db-password
  #volumes:
  #- /home/user/docker-ushahidi/platforms/src:/var/www/html
  links:
  - db:db

client:
  #build: client
  image: bennibu/ushahidi-client
  ports: 
  - 80:80
